-- Bare repo support for dotfiles
-- Instead of setting global GIT_DIR/GIT_WORK_TREE env vars (which break
-- plugins that run async git with their own cwd), we only configure
-- plugins that need bare repo awareness individually (e.g. gitsigns worktrees).
